export enum WeaponSpecial {
  // Todo this may be better as an optional int
  CatchFire = "Catch Fire",
  AutoAmmoRoll = "Auto Ammo Roll",
  GetsHot = "Gets Hot",
  ToxicDart = "Toxic Dart",
  NeedleInjuries = "Needle Injuries",
  Silent = "Silent",
  WebbedTargets = "Webbed Targets",
  Solvent = "Solvent",
  Capture = "Capture",
  KnockBack = "Knock Back",
  Pellets = "Pellets",
  CriticalShot = "Critical Shot",
  HighImpact = "High Impact",
  MoveAndFire = "Move And Fire",
  TerrifyingForce = "Terrifying Force",
  Nullify = "Nullify",
  Clumsy = "Clumsy",
  TwoHanded = "Two Handed",
  LoseDraw = "Lose Draw",
  MightyBlow = "Mighty Blow",
  Noisy = "Noisy",
  DualHanded = "Dual Handed",
  AutoOutOfAction = "Auto Out Of Action",
  ShockMaulInjury = "Shock Maul Injury",
  Parry = "Parry",
  Demolition = "Demolition",
  Smoke = "Smoke",
  Choke = "Choke",
  Scare = "Scare",
  Blind = "Blind",
  PlasmaBall = "Plasma Ball",
  MinusOneToHit = "Minus One To Hit",
  Hallucination = "Hallucination",
}
